kind: pipeline
type: docker
name: push

trigger:
  event:
    - push
    - pull_request

steps:
  - name: lint
    image: golangci/golangci-lint:v1.60.3
    environment:
      GH_TOKEN:
        from_secret: GH_READ_TOKEN
    commands:
      - echo "machine github.com login ${GH_USER} password ${GH_TOKEN}" >> $HOME/.netrc
      - golangci-lint run --timeout 600s --verbose ./...
      - rm $HOME/.netrc
    when:
      paths:
        include:
          - "**/*.go"
    depends_on:
      - clone

  - name: test
    image: golang:1.22
    commands:
      - make test || exit 1
    depends_on:
      - clone
    when:
      paths:
        include:
          - "**/*.go"
---
kind: pipeline
type: docker
name: versioning

trigger:
  paths:
    exclude:
      - "deploy/**"
  branch:
    - main
  event:
    - push

steps:
  - name: semantic-release
    image: node:21.3.0-alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GH_READ_TOKEN
      GIT_COMMITTER_NAME: deliveryhero-bot
      GIT_COMMITTER_EMAIL: bot.cicd.ext@deliveryhero.com
      GIT_AUTHOR_NAME: deliveryhero-bot
      GIT_AUTHOR_EMAIL: bot.cicd.ext@deliveryhero.com
    commands:
      - apk add git
      - npx semantic-release@latest

---
kind: pipeline
type: docker
name: release

trigger:
  event:
    - tag

features:
  docker-daemon@v1:
    enabled: true

steps:
  - name: push-tag
    image: plugins/gcr
    settings:
      registry: europe-docker.pkg.dev
      repo: dp-common-infra-5780/developer-platform-public/deliveryhero/gcp-config-connector-tagging-operator
      tags:
        - ${DRONE_TAG}
        - latest
      json_key:
        from_secret: DP_ARTIFACT_REGISTRY_JSON_KEY
