---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kms.cnrm.cloud.google.com
  resources:
  - kmskeyrings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kms.cnrm.cloud.google.com
  resources:
  - kmskeyrings/finalizers
  verbs:
  - update
- apiGroups:
  - redis.cnrm.cloud.google.com
  resources:
  - redisinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.cnrm.cloud.google.com
  resources:
  - redisinstances/finalizers
  verbs:
  - update
- apiGroups:
  - sql.cnrm.cloud.google.com
  resources:
  - sqlinstances
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - sql.cnrm.cloud.google.com
  resources:
  - sqlinstances/finalizers
  verbs:
  - update
- apiGroups:
  - storage.cnrm.cloud.google.com
  resources:
  - storagebuckets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - storage.cnrm.cloud.google.com
  resources:
  - storagebuckets/finalizers
  verbs:
  - update
- apiGroups:
  - tags.cnrm.cloud.google.com
  resources:
  - tagslocationtagbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
