apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gcp-config-connector-tagging-operator.fullname" . }}-manager-role
  labels:
  {{- include "gcp-config-connector-tagging-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kms.cnrm.cloud.google.com
  resources:
  - kmskeyrings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.cnrm.cloud.google.com
  resources:
  - storagebuckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tags.cnrm.cloud.google.com
  resources:
  - tagslocationtagbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gcp-config-connector-tagging-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "gcp-config-connector-tagging-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "gcp-config-connector-tagging-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "gcp-config-connector-tagging-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'