apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcp-config-connector-tagging-operator-metrics-auth-role
  labels:
  {{- include "gcp-config-connector-tagging-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gcp-config-connector-tagging-operator-metrics-auth-rolebinding
  labels:
  {{- include "gcp-config-connector-tagging-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gcp-config-connector-tagging-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: gcp-config-connector-tagging-operator-controller-manager
  namespace: '{{ .Release.Namespace }}'