apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-config-connector-tagging-operator-controller-manager
  labels:
  {{- include "gcp-config-connector-tagging-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}