name: Build And Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  REGISTRY: ghcr.io

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: "1.22"
  #         cache: true
  #     - name: Run golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.60.3
  #         args: --timeout 600s --verbose ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
          cache: true
      - name: Test
        run: make test

  release:
    name: Release
    needs: [test] #lint should be placed back
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: semantic
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMITTER_NAME: deliveryhero-bot
          GIT_COMMITTER_EMAIL: bot.cicd.ext@deliveryhero.com
          GIT_AUTHOR_NAME: deliveryhero-bot
          GIT_AUTHOR_EMAIL: bot.cicd.ext@deliveryhero.com

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        # if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/gcp-config-connector-tagging-operator:v1.0.0
          # ${{ steps.semantic.outputs.new_release_version }}
