name: Codacy Analysis

on:
  pull_request:
    branches: [main]
    # paths:
    #   - "**.go"
    types: [opened, synchronize, reopened, edited]

jobs:
  codacy-analysis:
    if: github.repository == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@97bf5df3c09e75f5bcd72695998f96ebd701846e
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.out
