name: Codacy Analysis

on:
  push:
    branches: [main]
    # paths:
    #   - "**.go"
  pull_request:
    branches: [main]
    # paths:
    #   - "**.go"

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    permissions:
      # These permissions are necessary for the Codacy Analysis CLI action to authenticate with the GitHub app
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@97bf5df3c09e75f5bcd72695998f96ebd701846e
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
